source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '15.0'
use_frameworks!

target 'Kitty' do
  # 不再需要火山引擎 SDK，直接使用 URLSession WebSocket
  # TTS 使用系统 AVSpeechSynthesizer
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end